### ISSUE TITLE
自动打卡方式Android实现参考

### ISSUE THREAD

**Issue by Sun020422** [SnapdragonLee/BUAA_AutoCheck#2]
可以考虑使用腾讯云函数运行，参见https://github.com/tienskowl/AutoReport

**Comment by SnapdragonLee** [comment]
谢谢了 感觉这个不失为一种全平台实现方案，但是使用对普通用户有一定门槛（ 其实云环境有很多都可以用）
我暂时看到了安卓端有  Auto.js pro 可以实现相关操作，只不过我不太想在这里推荐一个付费应用（甚至是破解过的，总感觉有些不妥），然后我又看到了 JSkit，以及 Tasker；但是实现起来还是比较麻烦，和你提供的这个解决方案耗时差不多，所以我会先标记

**Comment by Befod** [comment]
可以用 [termux](https://github.com/termux/termux-app#Termux-App-and-Plugins=)，
Termux 是一个 Android 下一个高级的终端模拟器，开源且不需要 root，支持 apt 管理软件包，十分方便安装软件包，完美支持 Python、 PHP、 Ruby、 Nodejs、 MySQL等。

**Comment by SnapdragonLee** [comment]
> Termux 是一个 Android 下一

不是很了解android系统，手头也没有可以测试的环境，可能也可以尝试一下类似于 linux 的方式？

**Comment by KZdavid** [comment]
我根据你的js代码改了个基于Auto.js的Android平台的实现，merge一下？https://github.com/SnapdragonLee/BUAA_AutoCheck/pull/3
你说的那个JSkit不太了解，不知道能不能实现自动。

**Comment by KZdavid** [comment]
https://github.com/SnapdragonLee/BUAA_AutoCheck/pull/3

**Comment by SnapdragonLee** [comment]
hello
我是snapdragonlee，我看到了您的提交，谢谢您！目前我手头没有设备，可以给我看一下具体的实现效果嘛？我之前其实有注意到auto.js，但是因为其是付费的
且普及率不高，所以放弃了这个方案。
我看了一下您的github，确定您应该是北航的同学，如果确定脚本可以跑，我就把您的提交直接合并了。
另外这个项目在 buaahub/awesome-buaa: buaa 北航 收集优秀的buaaer创造的实用的工具和脚本 (github.com)
<https://github.com/buaahub/awesome-buaa> 中有推荐，有兴趣的话可以加入 buaahub
组织，目前有200+人在所创建的tg群中。
再次感谢您的提交

KZdavid ***@***.***> 于2022年10月11日周二 22:40写道：

**Comment by SnapdragonLee** [comment]
> 我根据你的js代码改了个基于Auto.js的Android平台的实现，merge一下？#3 你说的那个JSkit不太了解，不知道能不能实现自动。

已经合并

**Comment by KZdavid** [comment]
谢谢merge！
我知道那个awesome-buaa我也在关注，感觉非常有用。我对您说的buaahub也很感兴趣，请问有加群链接吗？



发自我的小米手机
在 Snapdragon Lee ***@***.***>，2022年10月12日 08:16写道：

hello
我是snapdragonlee，我看到了您的提交，谢谢您！目前我手头没有设备，可以给我看一下具体的实现效果嘛？我之前其实有注意到auto.js，但是因为其是付费的
且普及率不高，所以放弃了这个方案。
我看了一下您的github，确定您应该是北航的同学，如果确定脚本可以跑，我就把您的提交直接合并了。
另外这个项目在 buaahub/awesome-buaa: buaa 北航 收集优秀的buaaer创造的实用的工具和脚本 (github.com)
<https://github.com/buaahub/awesome-buaa> 中有推荐，有兴趣的话可以加入 buaahub
组织，目前有200+人在所创建的tg群中。
再次感谢您的提交

KZdavid ***@***.***> 于2022年10月11日周二 22:40写道：

**Comment by SnapdragonLee** [comment]
hello，你可以查看 buaahub/readme: A Brief Introduction to BuaaHub (github.com)
<https://github.com/buaahub/readme> ，具体因为需要学校邮箱验证，所以我就不赘述了

KZdavid ***@***.***> 于2022年10月18日周二 19:38写道：
